final_project/urls.py
from django.contrib import admin 
from django.urls import path, include

from django.urls import include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fyp.urls', namespace='fyp')),
    path('', include('users.urls', namespace='users')),
    path('', include('payment.urls', namespace='payment'))
]

fyp/urls.py
from django.urls import path
from . import views

app_name = 'fyp'

urlpatterns = [
    path('home/<int:page>', views.home),
    path('', views.welcome, name='fyp-welcome'),
    path('home/search', views.search),
    
    
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.fyp_login, name='fyp-login'),
    path('logout/', views.fyp_logout, name='fyp-logout'),
    path('register/', views.register, name='fyp-register'),
    path('profile/', views.profile, name='fyp-profile'),
    path('edit-profile/<int:pk>/', views.edit_profile, name='fyp-edit_profile'),
    path('funds/', views.add_funds, name='fyp-add_funds'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User

class AppUser(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	phone = models.IntegerField()
	funds = models.IntegerField(blank=True,null=True,default=0)
	


 

users/forms.py
from django import forms
from django.contrib.auth.models import User
from users.models import AppUser
from django.contrib.auth.forms import UserCreationForm

class UserRegisterForm(UserCreationForm):
	email = forms.EmailField()

	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']

class AppUserRegister(forms.ModelForm):
	class Meta:
		model = AppUser
		fields = ['phone']

class LoginForm(forms.Form):
    username= forms.CharField(label="Username")
    password= forms.CharField(label='Password', widget=forms.PasswordInput)


class EditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email']

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from .forms import UserRegisterForm, LoginForm, EditForm, AppUserRegister
from .models import AppUser
# Create your views here.

def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        app_form = AppUserRegister(request.POST)
        if form.is_valid():
            user = form.save()
            appuser = app_form.save(commit=False)
            appuser.user = user
            appuser.save()
            username = form.cleaned_data.get('username') 
            login(request, user)
            messages.success(request, f'Account created for {username}! You are now able to log in')
            return redirect('/home/1')
        else:
            messages.warning(request, f'Your password does not meet the criteria!')
    form = UserRegisterForm()
    app_form = AppUserRegister()
    return render(request, 'users/register.html', {'form': form, 'app_form': app_form})

def fyp_login(request):
    form = LoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, f'You are logged in as { username }!!')
            return redirect('/home/1')
        else:
            messages.warning(request, f'The username or password is incorrect!')
    else:
        return render(request, 'users/login.html', context={"form": form})

    form = LoginForm()
    return render(request, 'users/login.html', context={"form": form})


def fyp_logout(request):
    logout(request)
    return render(request, 'users/logout.html')
    return redirect('fyp:fyp-logout')


def profile(request):
    appuser = AppUser.objects.get(user=request.user)
    # detail = User.objects.get(pk=pk)
    # if detail.is_superuser:
    #     other = None
    # else:
    #     other = AppUser.objects.get(user_id=pk)
    context = {
        "appuser": appuser
        }
    return render(request, 'users/profile.html', context)


def add_funds(request):
    previous_funds = AppUser.objects.get(user=request.user).funds
    if request.method == "POST":
        funds = int(request.POST['fund'])
        funds = funds + previous_funds
        AppUser.objects.filter(user=request.user).update(funds=funds)
        return profile(request)
    return render(request, 'users/add_funds.html')  


def edit_profile(request, pk):
    if request.method == "POST":
        form = EditForm(data = request.POST, instance = request.user)
        if form.is_valid():
            form.save()
            return redirect('users:fyp-profile')
    else:
        form = EditForm(instance = request.user)
        context={
            "form": form
        }
        return render(request, 'users/edit_profile.html',context)

users/templates/users/add_funds.html
{% extends "fyp/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<h1 class="text-center">Load Funds</h1>

<hr>
<h3>Choose your Bank</h3>
<div class="row pb-5">
    <div class="col-md-11">
    	<div class="card-header">
    	<div class="dropdown">
			  <!-- <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="dropdown-item">
			    Himalayan Bank Ltd
			  </button>
			  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
			    <a class="dropdown-item" href="#">Himalayan Bank Ltd</a>
			    <a class="dropdown-item" href="#">NIC Asia Bank Ltd</a>
			    <a class="dropdown-item" href="#">Nepal Investment Bank Ltd</a>
			    <a class="dropdown-item" href="#">Citizens Bank International Ltd</a>
			    <a class="dropdown-item" href="#">Sunrise Bank Ltd</a>
			    <a class="dropdown-item" href="#">Prime Commercial Bank Ltd</a>
			    <a class="dropdown-item" href="#">Century Commercial Bank Ltd</a>
			  </div> -->

			  <div class="form-group">
			        <label for="select-bank">Select Bank</label>
			        <select id="select-bank" class="form-control" >
			          <option>Himalayan Bank Ltd</option>
			          <option>NIC Asia Bank Ltd</option>
			          <option>Nepal Investment Bank Ltd</option>
			          <option>Citizens Bank International Ltd</option>
			          <option>Sunrise Bank Ltd</option>
			          <option>Prime Commercial Bank Ltd</option>
			          <option>Century Commercial Bank Ltd</option>
			        </select>
			      </div>
			</div>
			    	<form>
			  <div class="form-group">
			    <label for="exampleInputEmail1">Bank ID</label>
			    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
			    <small id="emailHelp" class="form-text text-muted">We'll never share your ID with anyone else.</small>
			  </div>
			  <div class="form-group">
			    <label for="exampleInputPassword1">Pin Code</label>
			    <input type="password" class="form-control" id="exampleInputPassword1">
			  </div>
			  <div class="form-group form-check">
			    <input type="checkbox" class="form-check-input" id="exampleCheck1">
			    <label class="form-check-label" for="exampleCheck1">I accept to load fund into my account!</label>
			  </div>
			</form>
		<form method="post">
		    {% csrf_token %}
		    <input type="text"  name="fund" placeholder="Enter Amount">
		    <button type="submit" class=" btn btn-primary">Add Amount </button>
		</form>
	</div>
	</div>
	 <div class="col-md-1">
            <div class="content-section " style="width: 350px;">
              <img src="https://magic1017fm.com/wp-content/uploads/2019/10/payment-background-design_1212-566.jpg" class="card-img-top" alt="...">
              <div class="card-body">
              <h4>Do Payment Now!</h4>
                <p class="card-text">Customer Selfie Payment :) </p>
              </div>
            </div>
     </div>  
</div>
{% endblock content %}

users/templates/users/edit_profile.html
{% extends "fyp/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
	<form method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		<fieldset class="form-group">
			<legend class="border-bottom mb-4"><b>Edit Profile </b> </legend>
			    
			{{ form | crispy }}
			
		</fieldset>
	    <button type="submit" class=" btn btn-primary"> Update Profile </button>
	</form>
</div>		
{% endblock content %}

users/templates/users/login.html
{% extends "fyp/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4"><b>Log In</b></legend>
				{{ form|crispy }}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">Log In</button>
			</div>
		</form>
		<div class="border-top pt-3">
			<small class="text-muted">Don't Have An Account?<a class="ml-2" href="{% url 'users:fyp-register' %}">Sign Up</small>
		</div>
	</div>
{% endblock content %}

users/templates/users/logout.html
{% extends "fyp/base.html" %}
{% block content %}
		<h2>You have been logged out!</h2>
		<div class="border-top pt-3">
			<small class="text-muted"><a href="{% url 'users:fyp-login' %}">Log In Again</small>
		</div>
	</div>
{% endblock content %}

users/templates/users/profile.html
{% extends "fyp/base.html" %}
{% load crispy_forms_tags %}
	{% block title %}
		View Profile
	{% endblock %}

{% block content %}
<h1 class="text-center">Profile</h1>

<hr>
<div class="row mb-5">
    <div class="col-md-11">
        <div class="card" style="width: 20rem;">
            <img src="https://www.windstream.com/getmedia/b2e4e38a-7cb6-4ca9-9544-54dfeaca6304/icon_user-circle.png.aspx?width=1520&height=980&ext=.png"
                class="card-img-top" alt="img">
            <div class="card-body" style="margin-bottom: -25px;">
                
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">Username: {{ user.username }}</li>
                <li class="list-group-item">Email: {{ user.email }}</li>
                
                
                <li class="list-group-item"> Balance : {{ appuser.funds }}</li>
                <li class="list-group-item"> Phone : {{ appuser.phone }}</li>
                <li class="list-group-item"><a href="{% url 'users:fyp-add_funds' %}"><button class="btn btn-primary btn-sm">Add Funds</button></a>
                <a href="/view-payment/1"><button class="btn btn-primary btn-sm">View Payments</button></a></li>
               
            
                <div class="container">
                
                    <a href="{% url 'users:fyp-edit_profile' user.pk %}"><button class="btn btn-primary btn-sm float-left mr-2"> Edit Profile</button></a>
                
                    <form method="POST" enctype="multipart/form-data" action="">
                        {% csrf_token %}
                        <button class="btn btn-info btn-sm float-left" type="submit"> Settings </button>
                    </form>
                </div>
                    
                
            </ul>
	 	</div>
    </div>
        <div class="col-md-1">
            <div class="content-section " style="width: 350px;">
              <img src="https://magic1017fm.com/wp-content/uploads/2019/10/payment-background-design_1212-566.jpg" class="card-img-top" alt="...">
              <div class="card-body">
              <h4>Do Payment Now!</h4>
                <p class="card-text">Customer Selfie Payment :) </p>
              </div>
            </div>
        </div>  
	

</div>
{% endblock content %}

users/templates/users/register.html
{% extends "fyp/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4"><b>Sign Up </b> </legend>
				{{ form|crispy }}
				{{ app_form|crispy }}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">Sign Up</button>
			</div>
		</form>
		<div class="border-top pt-3">
			<small class="text-muted">Already Have An Account?<a class="ml-2" href="{% url 'users:fyp-login' %}">Log In</small>
		</div>
	</div>
{% endblock content %}