final_project/urls.py
from django.contrib import admin 
from django.urls import path, include

from django.urls import include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fyp.urls', namespace='fyp')),
    path('', include('users.urls', namespace='users')),
    path('', include('payment.urls', namespace='payment'))
]

fyp/urls.py
from django.urls import path
from . import views

app_name = 'fyp'

urlpatterns = [
    path('home/<int:page>', views.home),
    path('', views.welcome, name='fyp-welcome'),
    path('home/search', views.search),
    
    
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.fyp_login, name='fyp-login'),
    path('logout/', views.fyp_logout, name='fyp-logout'),
    path('register/', views.register, name='fyp-register'),
    path('profile/', views.profile, name='fyp-profile'),
    path('edit-profile/<int:pk>/', views.edit_profile, name='fyp-edit_profile'),
    path('funds/', views.add_funds, name='fyp-add_funds'),
]

fyp/models.py
from django.db import models
from django.contrib.auth.models import User

  

# Create your models here.
	

class Services(models.Model):
    services_id = models.AutoField(primary_key=True)
    services_title = models.CharField(max_length=50)
    services_description = models.CharField(max_length=100)
    services_contact = models.CharField(max_length=20)
    services_img = models.CharField(max_length=100)

fyp/views.py
from django.shortcuts import render
from .models import Services
from django.core.paginator import Paginator
from django.db.models import Q

# Create your views here.
def home(request, page):
    services = Services.objects.all()
    paginator = Paginator(services, 3)
    services = paginator.get_page(page)
    context = {
        "services": services
    }
    return render(request, 'fyp/home.html', context)

def search(request):
	get_query = request.POST['q']
	match = Services.objects.filter(Q(services_title__icontains=get_query))
	context = {
		"services": match
	}
	return render(request, 'fyp/home.html', context)

def welcome(request):
    context = {
        "welcome": True
    }
    return render(request, 'fyp/welcome.html', context)

fyp/templates/fyp/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://use.fontawesome.com/releases/v5.11.0/css/all.css">
    <!-- <link rel="stylesheet" type="text/css" href="https://mdbootstrap.com/api/snippets/static/download/MDB-Pro_4.19.0/css/bootstrap.min.css"> -->
    <link rel="stylesheet" type="text/css" href="https://mdbootstrap.com/api/snippets/static/download/MDB-Pro_4.19.0/css/mdb.min.css">


   <link rel="stylesheet" type="text/css" href="{% static 'fyp/main.css' %}">


	{% if title %}
		<title>Customer Selfie Payment - {{ title }}</title>
	{% else %}
		<title>Customer Selfie Payment</title>
	{% endif %}
</head>
<body>
	<header class="site-header">
  <nav class="navbar navbar-expand-md navbar-dark bg-dark shadow-sm fixed-top"> 
    <div class="container">
      <a class="navbar-brand mr-4" href="{% url 'fyp:fyp-welcome' %}"><b>Customer Selfie Payment</b></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarToggle">
        <div class="navbar-nav mr-auto">
          <a class="nav-item nav-link" href=" "></a>
        </div>
        <!-- Navbar Right Side -->

        <div class="navbar-nav">
            {% if user.is_authenticated %}
                
                <a class="nav-item nav-link" href="/home/1">Payment</a>
               
             
                <a class="nav-item nav-link" href="{% url 'users:fyp-profile' %} ">Profile</a>
              
               
                <a class="nav-item nav-link" href="{% url 'users:fyp-logout' %}">Logout</a>
                
            {% else %}
                
                <a class="nav-item nav-link" href="{% url 'users:fyp-login' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'users:fyp-register' %}">Register</a>
                

            {% endif %}
        </div>
        
    </div>
  </nav>
</header>

<main role="main" class="container">

  <div class="row">
    <div class="col-md-8">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endfor %}
      {% endif %}
      {% block content %} {% endblock %}
    </div>
    
    </div>
  </div>
</main>

{% if welcome %}
{% else %}
<!-- Footer -->
<footer class="page-footer font-small special-color-dark pt-4">

  <!-- Footer Elements -->
  <div class="container">

    <!-- Social buttons -->
    <ul class="list-unstyled list-inline text-center mb-3">
      <li class="list-inline-item">
        <a class="btn-floating btn-fb mx-1" href="https://www.facebook.com">
          <i class="fab fa-facebook-f"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a class="btn-floating btn-tw mx-1" href="https://twitter.com">
          <i class="fab fa-twitter"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a class="btn-floating btn-gplus mx-1" href="https://myaccount.google.com">
          <i class="fab fa-google-plus-g"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a class="btn-floating btn-li mx-1" href="https://np.linkedin.com">
          <i class="fab fa-linkedin-in"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a class="btn-floating btn-dribbble mx-1" href="https://dribbble.com">
          <i class="fab fa-dribbble"> </i>
        </a>
      </li>
    </ul>
    <!-- Social buttons -->

  </div>
  <!-- Footer Elements -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="https://mdbootstrap.com/"> CSP.com</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->
{% endif %}
	
	<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  

</body>
</html>

fyp/templates/fyp/home.html
{% extends "fyp/base.html" %}
{% block content %}
	

 <title>Payment</title>
 <div class="row pb-10" style="width: 1000px;">
  <div class="col-md-11">
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" align="center">
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="https://visualmodo.com/wp-content/uploads/2019/01/PayPal-Payment-Requests-Usage-Guide.png" class="d-block w-100" alt="..." >
        </div>
        <div class="carousel-item">
          <img src="https://www.moneycrashers.com/wp-content/uploads/2019/02/automatic-bill-payment-plans-1200x630-cropped.jpg" class="d-block w-100" alt="..." >
        </div>
        <div class="carousel-item">
          <img src="https://www.imd.org/contentassets/8a4771252dff43e1b2131891ae5e68eb/tc045-19_facebook-linkedin-1200x630-1.jpg" class="d-block w-100" alt="..." >
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div> 
  </div>
  <div class="col-md-1">
    <div class="content-section " style="width: 250px;">
          <img src="https://lh3.googleusercontent.com/_j_9jVM50j43oII8sejBsK4DkHXxFw_MYUQOcHNjgX7SgJMQiLUsa8BuKWGK_84H_OE" class="card-img-top" alt="...">
          <div class="card-body">
          <h4>Available now!</h4>
            <p class="card-text">Watch your favourite movies now by paying with this application</p>
            <a href="#"><button class="btn btn-primary btn-sm">Learn More</button></a>
          </div>
        </div>
  </div>      
</div> 
<hr>
<br>
<h2 style="text-align: center">Our Services</h2>
<div class="row pb-7">
  <div class="col-md-11">
    <div class="card-header">


    {% for service in services %}
      <div class="card mb-3" style="max-width: 540px;">
        <div class="row no-gutters">
          <div class="col-md-4">
            <img src="{{ service.services_img }}" class="card-img" alt="...">
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <a href="pay/{{ service.services_id }}"><h5 class="card-title">{{ service.services_title }}</h5></a>
              <p class="card-text">{{ service.services_description }}</p>
              <p class="card-text"><small class="text-muted">Contact: {{ service.services_contact }}</small></p>
            </div>
          </div>
        </div>
      </div>
    {% empty %}
        There are no such services
    {% endfor %}

    <ul class="pagination">
        {% if services.has_previous %}
          <li class="page-item">
            <a class="page-link" href="/home/{{ services.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
        {% endif %}
        {% for num in services.paginator.page_range %}
          <li class="page-item {% if num == services.number %}active{% endif %}"><a class="page-link" href="/home/{{num}}">{{num}}</a></li>  
        {% endfor %}
        {% if services.has_next %}
          <li class="page-item">
            <a class="page-link" href="/home/{{ services.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
        {% endif %}
      </ul>
  </div>
  </div>
  <div class="col-md-1">
    <div class="content-section" style="width: 400px;">
      <h4>Find Here</h4>
      <p class='text-muted'>Search Services From Here...</p>
        <form action="/home/search" method="POST" class="form-inline my-2 my-lg-0">
          {% csrf_token %}
          <input name="q" value="" class="form-control m-0" type="search" placeholder="Search..." aria-label="Search">
          <button class="form-control btn btn-outline-success m-0" type="submit">Search</button>
        </form>
    </div>
       <div class="content-section text-white bg-info " style="width: 400px;">
            <h5 class="card-title text-white">About Us</h5>
            <p class="card-text">“Customer Selfie Payment” is facial authentication web-based application which helps user to make payment online by verifying their identity.  </p>
      </div> 
        <div class="content-section " style="width: 400px;">
          <img src="https://magic1017fm.com/wp-content/uploads/2019/10/payment-background-design_1212-566.jpg" class="card-img-top" alt="...">
          <div class="card-body">
          <h4>Do Payment Now!</h4>
            <p class="card-text">Customer Selfie Payment :) </p>
          </div>
        </div>

  </div>

</div>


{% endblock content %}   
   

fyp/templates/fyp/welcome.html
{% extends "fyp/base.html" %}
{% block content %}
<style>
    #bg{
        background:linear-gradient(rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.7)), url('static/fyp/pay.jpg') no-repeat;
        min-height: 980px;
        background-size: cover;
        background-attachment: fixed;
        overflow: hidden;
    }
</style>
<body id="bg">
    <div class="container" style="margin-left: 30%; margin-top: 20%;">
        <h1 class="title text-center">
            <strong style="align:text-center; color: #fff; font-family: Times New Roman; font-size: 45px;">Online Payment Gateway <br><br> Make Payments Online Instantly</strong>
        </h1>
        {% if not user.is_authenticated %}
        <div class="text-center mt-4">
            <a href="../login"><button class="btn btn-primary btn-large" style="margin-right: 50px;">Login</button></a>
            <a href="../register"><button class="btn btn-success btn-large">Register</button></a>
        </div>
        {% else %}
        <div class="text-center mt-4">
            <a href="/home/1"><button class="btn btn-primary btn-large" style="margin-right: 50px;">Payment</button></a>
            <a href="{% url 'users:fyp-profile' %}"><button class="btn btn-success btn-large">Profile</button></a>
        </div>
        {% endif %}
    </div>
</body>
{% endblock content %}